const $=s=>document.querySelector(s);const app=$('#app');
const courses=[
{id:'s1-fon',title:'Fundamentals of Nursing I',icon:'✚',credits:'3 credits • 2 theory • 1 skills lab',color:'#0b7f72'},
{id:'s1-anatomy',title:'Anatomy & Physiology I',icon:'⚕',credits:'3 credits • 2.5 theory • 0.5 lab',color:'#326a9c'},
{id:'s1-microbiology',title:'Microbiology',icon:'◉',credits:'2 credits • 1.5 theory • 0.5 lab',color:'#7552a3'},
{id:'s1-biochemistry',title:'Biochemistry',icon:'⬡',credits:'2 credits • theory and lab',color:'#c27924'},
{id:'s1-english',title:'Functional English',icon:'A',credits:'3 credits • communication',color:'#b64f61'},
{id:'s1-ict',title:'Information & Communication Technology',icon:'⌘',credits:'3 credits • digital skills',color:'#287c92'},
{id:'s1-pakistan',title:'Ideology & Constitution of Pakistan',icon:'★',credits:'2 credits • civic studies',color:'#527a45'}];
let pkg,manifest,route={page:'home'},exam=null;
const labels={lesson:'Lessons',mcq:'Practice MCQs',flashcard:'Flashcards',written_question:'Written questions',course_test:'Course tests'};
const icons={lesson:'▤',mcq:'✓',flashcard:'▱',written_question:'✎',course_test:'◷'};
const classes={lesson:'lessons',mcq:'mcqs',flashcard:'flashcards',written_question:'written',course_test:'tests'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function titleOf(x){return x.body.title||x.body.stem||x.body.front||x.body.question||x.id}
function shell(content,active='learn'){app.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><span class="logo">♥</span><span>NURSEPATH<br><small style="color:var(--teal)">Pakistan</small></span></div><span class="owner-pill">Semester 1 • Published</span></header><main>${content}</main><nav class="bottom"><button class="navbtn ${active==='home'?'active':''}" data-home>⌂<br>Today</button><button class="navbtn ${active==='learn'?'active':''}" data-learn>▤<br>Learn</button><button class="navbtn" data-practice>✓<br>Practice</button></nav></div>`;bindNav()}
function bindNav(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=home);document.querySelectorAll('[data-learn]').forEach(x=>x.onclick=learn);document.querySelectorAll('[data-practice]').forEach(x=>x.onclick=()=>startExam(courses[0]))}
async function load(){try{manifest=await fetch(`content/manifest.json?t=${Date.now()}`).then(r=>r.json());const s=manifest.semesters.find(x=>x.semester===1);pkg=await fetch(s.packageUrl).then(r=>r.json());learn()}catch(e){app.innerHTML=`<div class="empty"><h2>Unable to load study material</h2><p>${esc(e.message)}</p></div>`}}
function home(){shell(`<section class="hero"><div><div class="eyebrow">Your nursing journey</div><h1>Study smarter.<br>Care with confidence.</h1><p>Everything for Semester 1 is organized, unlocked and ready for active recall.</p><button class="primary" data-go>Continue learning</button></div><div class="hero-stat"><span>Published library</span><strong>${pkg.itemCount.toLocaleString()}</strong><span>verified learning items</span></div></section><div class="section-head"><div><h2>Quick practice</h2><p>Train with real exam-style questions.</p></div></div><button class="module mcqs" data-exam><span class="icon">✓</span><strong>Start a 10-question test</strong><small>Timed • scored • rationales included</small></button>`,'home');$('[data-go]').onclick=learn;$('[data-exam]').onclick=()=>startExam(courses[0])}
function learn(){shell(`<section class="hero"><div><div class="eyebrow">Semester 1 • Fully unlocked</div><h1>Your complete nursing study library.</h1><p>Choose a course to open its lessons, flashcards, written practice and exam-mode MCQs.</p></div><div class="hero-stat"><span>Total material</span><strong>${pkg.itemCount.toLocaleString()}</strong><span>items • static low-cost access</span></div></section><div class="section-head"><div><h2>Semesters</h2><p>New semesters appear automatically after publishing.</p></div></div><div class="semester-strip">${manifest.semesters.map(s=>`<span class="sem ${s.semester===1?'active':''} ${s.status==='generating'?'generating':''}">Semester ${s.semester} • ${s.status}</span>`).join('')}</div><div class="section-head"><div><h2>Semester 1 courses</h2><p>All published courses are open.</p></div></div><div class="grid">${courses.map(c=>{const n=pkg.items.filter(x=>x.courseId===c.id).length;return `<button class="course" data-course="${c.id}"><span class="course-icon" style="background:${c.color}18;color:${c.color}">${c.icon}</span><h3>${esc(c.title)}</h3><div class="course-meta">${esc(c.credits)} • ${n} items</div><div class="unlocked"><span>● Unlocked</span><span>Open →</span></div></button>`}).join('')}</div>`);document.querySelectorAll('[data-course]').forEach(x=>x.onclick=()=>coursePage(courses.find(c=>c.id===x.dataset.course)))}
function coursePage(c){const items=pkg.items.filter(x=>x.courseId===c.id),groups=Object.groupBy(items,x=>x.contentType);shell(`<button class="back" data-back>← All courses</button><section class="course-hero" style="background:linear-gradient(135deg,${c.color},var(--navy))"><div><div class="eyebrow">Semester 1 • Unlocked</div><h1>${esc(c.title)}</h1><p>${esc(c.credits)}</p></div><div><div class="course-count">${items.length}</div><small>study items</small></div></section><div class="section-head"><div><h2>Study modules</h2><p>Choose how you want to learn today.</p></div></div><div class="module-grid">${['lesson','mcq','flashcard','written_question','course_test'].filter(t=>groups[t]?.length).map(t=>`<button class="module ${classes[t]}" data-module="${t}"><span class="icon">${icons[t]}</span><strong>${labels[t]}</strong><small>${groups[t].length} items ${t==='mcq'?'• timed test available':''}</small></button>`).join('')}</div>`,`learn`);$('[data-back]').onclick=learn;document.querySelectorAll('[data-module]').forEach(x=>x.onclick=()=>x.dataset.module==='mcq'?startExam(c):listPage(c,x.dataset.module,groups[x.dataset.module]))}
function listPage(c,type,items){shell(`<button class="back" data-back>← ${esc(c.title)}</button><div class="section-head"><div><div class="eyebrow" style="color:var(--teal)">${esc(c.title)}</div><h1>${labels[type]}</h1><p>${items.length} organized study items</p></div>${type==='mcq'?'<button class="primary" data-exam>Start test mode</button>':''}</div><div class="content-list">${items.map((x,i)=>`<button class="item" data-item="${i}"><span><b>${esc(titleOf(x))}</b><small>${esc(x.body.difficulty||x.risk.replaceAll('_',' '))}</small></span><span>→</span></button>`).join('')}</div>`);$('[data-back]').onclick=()=>coursePage(c);if($('[data-exam]'))$('[data-exam]').onclick=()=>startExam(c);document.querySelectorAll('[data-item]').forEach(x=>x.onclick=()=>reader(c,type,items,items[+x.dataset.item]))}
function reader(c,type,items,item){if(type==='lesson')return lessonReader(c,items,item);if(type==='flashcard')return flashcardReader(c,items,item);if(type==='written_question')return writtenReader(c,items,item);if(type==='course_test')return testBrief(c,items,item);genericReader(c,type,items,item)}
function lessonReader(c,items,item){const b=item.body;const list=(xs)=>`<ul class="clean-list">${(xs||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;shell(`<button class="back" data-back>← Lessons</button><article class="reader"><header class="lesson-head"><div class="eyebrow">${esc(b.unitTitle||c.title)}</div><h1>${esc(b.title||titleOf(item))}</h1><p>A guided nursing lesson with objectives, explanations and revision points.</p></header>${b.objectives?.length?`<section class="objective-box"><h2>What you will be able to do</h2>${list(b.objectives)}</section>`:''}${(b.sections||[]).map((s,i)=>`<section class="lesson-section"><span>${String(i+1).padStart(2,'0')}</span><div><h2>${esc(s.heading)}</h2><p>${esc(s.text)}</p></div></section>`).join('')}${b.keyTerms?.length?`<section><div class="section-head"><div><div class="eyebrow">Quick reference</div><h2>Key terms</h2></div></div><div class="terms">${b.keyTerms.map(x=>`<div class="term"><b>${esc(x.term)}</b><p>${esc(x.definition)}</p></div>`).join('')}</div></section>`:''}${b.summaryPoints?.length?`<section class="summary-box"><h2>Lesson summary</h2>${list(b.summaryPoints)}</section>`:''}${b.cautions?.length?`<aside class="caution"><b>Clinical safety notes</b>${list(b.cautions)}</aside>`:''}${b.sourceIds?.length?`<p class="source-line">Reviewed learning sources: ${b.sourceIds.map(esc).join(' · ')}</p>`:''}</article>`);$('[data-back]').onclick=()=>listPage(c,'lesson',items)}
function flashcardReader(c,items,item){const b=item.body;shell(`<button class="back" data-back>← Flashcards</button><article class="reader"><div class="lesson-head"><div class="eyebrow">Active recall • ${esc(b.difficulty||'study')}</div><h1>Tap the card when you are ready</h1></div><div class="flashcard-wrap"><button class="flashcard" data-reveal><small>QUESTION</small><strong>${esc(b.front)}</strong><span>Tap to reveal answer</span><div class="flash-answer"><small>ANSWER</small><strong>${esc(b.back)}</strong></div></button></div></article>`);$('[data-back]').onclick=()=>listPage(c,'flashcard',items);$('[data-reveal]').onclick=e=>e.currentTarget.classList.toggle('revealed')}
function writtenReader(c,items,item){const b=item.body,key=`nursepath-attempt-${item.id}`,saved=localStorage.getItem(key)||'';shell(`<button class="back" data-back>← Written questions</button><article class="reader written-card"><div class="eyebrow">Written practice • ${esc(b.difficulty||'study')}</div><div class="marks">${esc(b.marks||'Practice')} ${b.marks?'marks':''}</div><h1>${esc(b.question)}</h1><label class="answer-label" for="attempt">Your answer</label><textarea id="attempt" class="answer-area" placeholder="Type your attempted answer here…">${esc(saved)}</textarea><div class="exam-actions"><button class="secondary" data-save>Save my attempt</button><button class="primary" data-reveal>Reveal marking points</button></div><div class="model-answer" data-model><h2>Key points expected</h2>${b.answerPoints?.length?`<ol>${b.answerPoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'<p>No marking guide is available yet.</p>'}</div></article>`);$('[data-back]').onclick=()=>listPage(c,'written_question',items);$('[data-save]').onclick=()=>{localStorage.setItem(key,$('#attempt').value);$('[data-save]').textContent='Attempt saved ✓'};$('[data-reveal]').onclick=()=>{$('[data-model]').classList.toggle('open');$('[data-reveal]').textContent=$('[data-model]').classList.contains('open')?'Hide marking points':'Reveal marking points'}}
function testBrief(c,items,item){const b=item.body;shell(`<button class="back" data-back>← Course tests</button><article class="reader exam-brief"><div class="eyebrow">Full mock assessment</div><h1>${esc(b.title||titleOf(item))}</h1><div class="exam-facts"><div class="exam-fact"><strong>${esc(b.durationMinutes||60)}</strong><span>minutes</span></div><div class="exam-fact"><strong>${esc(b.questionCount||50)}</strong><span>questions</span></div></div>${b.instructions?.length?`<section class="objective-box"><h2>Before you begin</h2><ul class="clean-list">${b.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${b.blueprint?.length?`<section><div class="section-head"><div><h2>Exam blueprint</h2><p>Topics covered in this mock assessment</p></div></div><div class="blueprint">${b.blueprint.map(x=>`<div class="blueprint-row"><b>${esc(x.topic)}</b><span>${esc(x.questionCount)} questions · ${esc(x.difficulty)}</span></div>`).join('')}</div></section>`:''}<button class="primary" data-start>Start full mock exam</button></article>`);$('[data-back]').onclick=()=>listPage(c,'course_test',items);$('[data-start]').onclick=()=>startExam(c,{count:b.questionCount||50,minutes:b.durationMinutes||60})}
function genericReader(c,type,items,item){const skip=['title','stem','front','question','correctIndex'];const readable=v=>Array.isArray(v)?v.map((x,i)=>`${i+1}. ${typeof x==='string'?x:Object.values(x).join(' — ')}`).join('\n'):typeof v==='object'?Object.values(v).join(' — '):v;shell(`<button class="back" data-back>← ${labels[type]}</button><article class="reader"><div class="eyebrow">${labels[type]} • ${esc(item.body.difficulty||'study')}</div><h1>${esc(titleOf(item))}</h1>${Object.entries(item.body).filter(([k])=>!skip.includes(k)).map(([k,v])=>`<div class="field"><label>${esc(k.replaceAll('_',' '))}</label><p>${esc(readable(v))}</p></div>`).join('')}</article>`);$('[data-back]').onclick=()=>listPage(c,type,items)}
function startExam(c,settings={}){const all=pkg.items.filter(x=>x.courseId===c.id&&x.contentType==='mcq');if(!all.length)return coursePage(c);const count=Math.min(settings.count||10,all.length),questions=[...all].sort(()=>Math.random()-.5).slice(0,count),seconds=settings.minutes?settings.minutes*60:questions.length*90;exam={c,questions,index:0,answers:Array(questions.length).fill(null),seconds,timer:setInterval(()=>{exam.seconds--;const el=$('[data-time]');if(el)el.textContent=time(exam.seconds);if(exam.seconds<=0)finishExam()},1000)};renderQuestion()}
const time=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function renderQuestion(){const {c,questions,index,answers}=exam,q=questions[index];shell(`<div class="exam-shell"><button class="back" data-exit>← Exit test</button><div class="exam-top"><div><div class="eyebrow" style="color:var(--teal)">${esc(c.title)}</div><h2>Timed practice test</h2></div><div class="timer">◷ <span data-time>${time(exam.seconds)}</span></div></div><div class="progress"><i style="width:${((index+1)/questions.length)*100}%"></i></div><section class="question-card"><div class="qnum">Question ${index+1} of ${questions.length} • ${esc(q.body.difficulty||'mixed')}</div><h2>${esc(q.body.stem)}</h2><div class="options">${q.body.options.map((o,i)=>`<button class="option ${answers[index]===i?'selected':''}" data-option="${i}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="exam-actions"><button class="secondary" data-prev ${index===0?'disabled':''}>Previous</button><button class="primary" data-next ${answers[index]===null?'disabled':''}>${index===questions.length-1?'Finish test':'Next question'}</button></div></section></div>`,'practice');$('[data-exit]').onclick=()=>{clearInterval(exam.timer);coursePage(c)};document.querySelectorAll('[data-option]').forEach(x=>x.onclick=()=>{answers[index]=+x.dataset.option;renderQuestion()});$('[data-prev]').onclick=()=>{exam.index--;renderQuestion()};$('[data-next]').onclick=()=>index===questions.length-1?finishExam():(exam.index++,renderQuestion())}
function finishExam(){if(!exam)return;clearInterval(exam.timer);const {c,questions,answers}=exam;const correct=questions.filter((q,i)=>answers[i]===q.body.correctIndex).length,pct=Math.round(correct/questions.length*100);shell(`<div class="exam-shell"><section class="result"><div class="eyebrow" style="color:var(--teal)">Test completed</div><h1>${pct>=80?'Excellent clinical recall!':pct>=60?'Good progress—keep practicing.':'Let’s strengthen the foundations.'}</h1><div class="score-ring" style="--score:${pct*3.6}deg"><strong>${pct}%</strong></div><p>${correct} correct out of ${questions.length}</p><button class="primary" data-again>Try another test</button><button class="secondary" data-course>Return to course</button></section><div class="section-head"><div><h2>Answer review</h2><p>Understand every answer before moving on.</p></div></div>${questions.map((q,i)=>`<div class="review ${answers[i]===q.body.correctIndex?'correct':'wrong'}"><b>${i+1}. ${esc(q.body.stem)}</b><p>Your answer: ${answers[i]===null?'Not answered':esc(q.body.options[answers[i]])}</p><p><strong>Correct:</strong> ${esc(q.body.options[q.body.correctIndex])}</p><p>${esc(q.body.rationale)}</p></div>`).join('')}</div>`,'practice');$('[data-again]').onclick=()=>startExam(c);$('[data-course]').onclick=()=>coursePage(c);exam=null}
load();
